### PR TITLE
Removed Image Assets and moved to icons class

### PR DESCRIPTION
**Pull request by raziqfarid**
#3 

Removed Image Assets and moved to icons class

Screenshot_20201028-125816
Screenshot_20201028-125839

### CODE REVIEW

**Review by shubhangi-singh21 — CHANGES_REQUESTED** [review]
LGTM! Please decrease the size of add_circle in proportion to other icons, the rest is fine👍

**Comment by raziqfarid** [comment]
@shubhangi-singh21 The size of add_circle is decreased to 50.0. Couldn't reduce further as the user may find it difficult to notice it.

**Review by shubhangi-singh21 — APPROVED** [review]

**Comment by raziqfarid** [comment]
@shubhangi-singh21 As of now, it showing invalid in hacktoberfest site. Can you please change the label from "hacktoberfest accepted" to "hacktoberfest-accepted"

**Comment by raziqfarid** [comment]
@shubhangi-singh21 Can you please replace the " " with "-" in the label i.e from "hacktoberfest accepted" to "hacktoberfest-accepted"

**Comment by raziqfarid** [comment]
@shubhangi-singh21  Can you please replace the " " with "-" in the label i.e from "hacktoberfest accepted" to "hacktoberfest-accepted"

**Pull request merged**
